"""Rework items as reusable resources

Revision ID: 11fc0bf20cf7
Revises: 754da8f98aa6
Create Date: 2026-08-29 13:34:11.184809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11fc0bf20cf7'
down_revision = '754da8f98aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'item_id', name='uq_case_items_case_item')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_items_owner_id_users', 'users', ['owner_id'], ['id']
        )
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('case_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(
            'fk_items_created_by_id_users', 'users', ['created_by_id'], ['id']
        )
        batch_op.create_foreign_key(
            'fk_items_case_id_cases', 'cases', ['case_id'], ['id']
        )
        batch_op.drop_column('owner_id')

    op.drop_table('case_items')
    # ### end Alembic commands ###
