"""Add encryption salt to items

Revision ID: 2ab899f316b2
Revises: 11fc0bf20cf7
Create Date: 2026-09-04 09:40:24.901792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab899f316b2'
down_revision = '11fc0bf20cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption_salt', sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('encryption_salt')

    # ### end Alembic commands ###
